[workspace]
resolver = "2"

[package]
name = "spark-sharing"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[features]
default = []
spark-transport = ["dep:spark-core"]

[dependencies]
async-trait = "0.1"
lantern-unbounded = { git = "https://github.com/getlantern/unbounded-rs", rev = "e6296614ed7d42a1d9fbeccf88a7ed8ee148cbfa", default-features = false }
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
rcgen = "0.13"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
serde_json = "1"
spark-core = { path = "../core", optional = true }
thiserror = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "sync", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
tokio-util = "0.7"
webpki-roots = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
overflow-checks = false
