[package]
name = "spark-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "spark_service"
path = "src/lib.rs"

[dependencies]
spark-ipc = { path = "../ipc", features = ["stream"] }
tokio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
