[package]
name = "spark-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "spark"
path = "src/main.rs"

[dependencies]
spark-core = { path = "../core" }
spark-ipc = { path = "../ipc", features = ["stream"] }
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
bytes.workspace = true

[features]
anytls = ["spark-core/anytls"]
system-stack = ["spark-core/system-stack"]
bootstrap-dns = ["spark-core/bootstrap-dns"]
multi-server = ["spark-core/multi-server"]
fronted-meek = ["spark-core/fronted-meek"]
