[package]
name = "spark-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "spark_core"
path = "src/lib.rs"

[dependencies]
netstack-smoltcp.workspace = true
tokio.workspace = true
futures.workspace = true
tun-rs.workspace = true
async-trait.workspace = true
socket2.workspace = true
libc.workspace = true
bytes.workspace = true
tracing.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
ring.workspace = true
