// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'control.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SparkBridge>>
abstract class SparkBridge implements RustOpaqueInterface {
  /// Bring the tunnel up.
  Future<void> connect();

  /// Tear the tunnel down.
  Future<void> disconnect();

  /// Bind to a service control endpoint (a unix-socket path on unix, a named pipe on Windows).
  /// Does not connect until a method is called. Synchronous so Dart builds it without `await`.
  factory SparkBridge({required String socketPath}) => RustLib.instance.api
      .crateApiControlSparkBridgeNew(socketPath: socketPath);

  /// Fetch the current tunnel status.
  Future<BridgeStatus> status();
}

@freezed
sealed class BridgeError with _$BridgeError implements FrbException {
  const BridgeError._();

  const factory BridgeError.unauthorized() = BridgeError_Unauthorized;
  const factory BridgeError.unsupportedVersion() =
      BridgeError_UnsupportedVersion;
  const factory BridgeError.invalidRequest() = BridgeError_InvalidRequest;
  const factory BridgeError.notConnected() = BridgeError_NotConnected;
  const factory BridgeError.internal({required String message}) =
      BridgeError_Internal;

  /// Could not reach or talk to the service (connect failed, closed mid-call, unexpected reply).
  const factory BridgeError.transport({required String message}) =
      BridgeError_Transport;
}

/// Tunnel lifecycle state — mirrors [`spark_ipc::TunnelState`] and the Dart `TunnelState`.
enum BridgeState { disconnected, connecting, connected, disconnecting, failed }

/// A status snapshot — mirrors [`spark_ipc::TunnelStatus`].
class BridgeStatus {
  final BridgeState state;

  /// The kill-switch failed open and traffic is routing directly — the UI must surface this.
  final bool directFallback;

  const BridgeStatus({required this.state, required this.directFallback});

  @override
  int get hashCode => state.hashCode ^ directFallback.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeStatus &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          directFallback == other.directFallback;
}
